apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository

metadata:
  name: helm-flux-gitops
  namespace: flux-system

spec:
  interval: 1m
  url: https://github.com/shivawmm/helm-flux-gitops
  ref:
    branch: main