replicaCount: 2

image:
  repository: shivawmm1810/quote-app
  tag: "309aa94e0a4d54f1d3687b9428a74951ffb25a45"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

containerPort: 80

environment: development

ingress:
  enabled: true
  className: nginx
  host: quote-app.local

resources:
  limits:
    cpu: 200m
    memory: 256Mi

  requests:
    cpu: 100m
    memory: 128Mi