replicaCount: 2

image:
  repository: shivawmm1810/quote-app
  tag: "9973a182bf4f5a08da008d85f1b7c3b57495dfc9"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

containerPort: 80

environment: development

ingress:
  enabled: true
  className: nginx
  host: quote-app.local

resources:
  limits:
    cpu: 200m
    memory: 256Mi

  requests:
    cpu: 100m
    memory: 128Mi