replicaCount: 2

image:
  repository: shivawmm1810/quote-app
  tag: "74d249aabb4d24134d1202ea136f854bcf8901c0"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

containerPort: 80

environment: development

ingress:
  enabled: true
  className: nginx
  host: quote-app.local

resources:
  limits:
    cpu: 200m
    memory: 256Mi

  requests:
    cpu: 100m
    memory: 128Mi