apiVersion: v1
kind: Service

metadata:
  name: {{ include "quote-app.fullname" . }}
  namespace: helm-flux-demo

spec:
  type: {{ .Values.service.type }}

  selector:
    app: quote-app

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}